include:
    ### ProMicro_Dongle START ###
    # NICE x PUCHI and nice_oled + rgb
  - board: nice_nano_v2
    shield: corne_left nice_oled
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Corne_Oled_RGB\"
    artifact-name: nice_corne_left_oled_rgb
    snippet: rgb-config studio-rpc-usb-uart
  - board: puchi_ble_v1
    shield: corne_right nice_oled
    snippet: rgb-config
    artifact-name: nice_corne_right_oled_rgb
    ### Pro Micro END ###
  ### SETTINGS_RESET START ###
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nice_settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: xiao_settings_reset
  - board: puchi_ble_v1
    shield: settings_reset
    artifact-name: puchi_settings_reset
  ### SETTINGS_RESET END ###
